### ISSUE TITLE
VectorChord Queries Extremely Slow Compared to pgvecto.rs (~7.5M Entries, v0.2.1 in Docker)

### ISSUE THREAD

**Issue by NetroScript** [tensorchord/VectorChord#208]
I've recently migrated my image similarity database at home from `pgvecto.rs` to `VectorChord`, using the latest Docker image (`tensorchord/vchord-postgres:pg16-v0.2.1`). Since migrating, I’ve experienced significantly slower query times—often magnitudes slower than before—despite utilizing indexed queries.

**Database & Setup Details:**  
_(click to expand)_  
<details>

- **Docker image:** `tensorchord/vchord-postgres:pg16-v0.2.1`
- **Database Size:** ~7.5 million entries.
- **Hardware:**
  - 12-core CPU
  - 128 GB RAM
  - HDDs using additional memory cache
- **Docker Compose Configuration:**
  
```yaml
version: "3.8"
name: image-db
services:
  db:
    image: tensorchord/vchord-postgres:pg16-v0.2.1
    restart: always
    shm_size: 72gb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5569:5432
    volumes:
      - /mnt/data/databases/image-data:/var/lib/postgresql/data/
    command:
      - postgres
      - -c
      - max_connections=72
      - -c
      - shared_buffers=48GB
      - -c
      - effective_cache_size=112GB
      - -c
      - maintenance_work_mem=2GB
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - wal_buffers=16MB
      - -c
      - default_statistics_target=100
      - -c
      - random_page_cost=4
      - -c
      - effective_io_concurrency=2
      - -c
      - work_mem=209715kB
      - -c
      - huge_pages=try
      - -c
      - min_wal_size=1GB
      - -c
      - max_wal_size=4GB
      - -c
      - max_worker_processes=4
      - -c
      - max_parallel_workers_per_gather=2
      - -c
      - max_parallel_workers=4
      - -c
      - max_parallel_maintenance_workers=2
      - -c
      - vchordrq.prewarm_dim=64,128,256,384,512,768,1024,1152,1536
      - -c
      - shared_preload_libraries=vchord.so,pg_stat_statements
      - -c
      - search_path="public,vchord"
```
</details>

---

**Table & Index Definition:**  
_(click to expand)_  
<details>

```sql
CREATE TABLE "ImageEmbedding" (
    id serial PRIMARY KEY,
    "mediaId" text NOT NULL REFERENCES "Media" ON UPDATE CASCADE ON DELETE CASCADE,
    embeddings vector(1152) NOT NULL
);

ALTER TABLE "ImageEmbedding" OWNER TO postgresql_db_user;

CREATE UNIQUE INDEX "ImageEmbedding_mediaId_key"
    ON "ImageEmbedding" ("mediaId");

CREATE INDEX "ImageEmbedding_mediaId_idx"
    ON "ImageEmbedding" ("mediaId");

CREATE INDEX "ImageEmbedding_embeddings_vchordrq" 
ON "ImageEmbedding" USING vchordrq ("embeddings" vector_cosine_ops) 
WITH (options = $$
residual_quantization = false
[build.internal]
lists = [20000]
spherical_centroids = true
$$);
```
</details>

---

**Example Query (Simple case):**

Even the simplest similarity query:

```sql
SET vchordrq.probes = 500; -- <3% of lists

SELECT * FROM "ImageEmbedding"
ORDER BY "embeddings" <=> ${embedding}::vector
LIMIT 25;
```

is very slow with an execution time of typically **6-60 seconds** (previously near-instant with pgvecto.rs).
CPU and disk I/O utilization remain close to non-existent during the query.

---

**Query Plan (500 probes):**

```
Limit  (cost=0.00..0.60 rows=25 width=67) (actual time=349.245..6114.847 rows=25 loops=1)
  Output: id, "mediaId", embeddings, ((embeddings <=> '[ ... ]'::vector))
  ->  Index Scan using "ImageEmbedding_embeddings_vchordrq" on public."ImageEmbedding"  (cost=0.00..174736.06 rows=7313205 width=67) (actual time=349.243..6114.812 rows=25 loops=1)
        Output: id, "mediaId", embeddings, (embeddings <=> '[ ... ]'::vector)
        Order By: ("ImageEmbedding".embeddings <=> '[ ... ]'::vector)
Planning Time: 0.735 ms
Execution Time: 6115.028 ms
```

---

**Query Plan (2000 probes, ~10% lists, >120s):**  
_(click to expand)_

<details>

```
Limit  (cost=0.00..0.60 rows=25 width=67) (actual time=2210.406..122746.671 rows=25 loops=1)
  Output: id, "mediaId", embeddings, ((embeddings <=> '[ ... ]'::vector))
  ->  Index Scan using "ImageEmbedding_embeddings_vchordrq" on public."ImageEmbedding"  (cost=0.00..174752.84 rows=7313907 width=67) (actual time=2210.400..122746.392 rows=25 loops=1)
        Output: id, "mediaId", embeddings, (embeddings <=> '[ ... ]'::vector)
        Order By: ("ImageEmbedding".embeddings <=> '[ ... ]'::vector)
Planning Time: 0.526 ms
Execution Time: 122748.494 ms
```
</details>

---

**Additional Notes:**

- Query speed doesn't significantly improve with different combinations of `probes` (tested ranges 15-3000) and `epsilon` (tested 1.0 - 1.9).
- The index was rebuilt after adding multiple million new embeddings to ensure balanced lists. However, performance did not improve noticeably.
- Hardware does not appear bottlenecked.
- I have a second table with an embedding with 512 dimensions. It is slightly faster, but similarly very slow compared to the previous HNSW-Index in `pgvecto.rs`.

---

**Expected Behavior:**

I expect queries utilizing the VChordRQ index to be at least in a comparable performance range to the previously used HNSW index provided by `pgvecto.rs`. Currently, query performance is prohibitively slow for practical use.
But the indexing speed is much higher, the disk space much lower, and the CPU usage also much lower, so that is great 👍.

---

**Questions:**

I assume I am doing something wrong, but as far as I can tell from the currently available documentation I did everything as advised / documented. 

Do you perhaps have any idea if I am missing something crucial in my configuration or usage?

---

Thanks in advance for your help!
